### ISSUE TITLE
Add DataTables library

### ISSUE THREAD

**Issue by LucileDT** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/huntington-avenir-bdd#18]
# Context
We want to be able to search in lists, have pagination and other features on our tables. For this, the DataTables library is very useful. We need to install it.

# Todo
- [x] install DataTables
- [x] configure default DataTables
  - [x] action buttons (copy, export)
  - [x] search field
  - [x] pagination
  - [x] which columns are 
    - [x] searchable
    - [x] exportable
    - [x] movable
