### ISSUE TITLE
Add user fields corresponding to the existing database

### ISSUE THREAD

**Issue by LucileDT** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/huntington-avenir-bdd#27]
# Context
As we are working with an existing (but old) application, we need to list then add the existing database fields corresponding to the users.

# Todo 
- [x] list of the existing fields
- [x] add those fields to the User class
- [x] show the fields in the app:
  - [x] mockups of the different pages
  - [x] edition of the different pages

**Comment by LucileDT** [comment]
@Parmifer @sapphaos I think we need to make a difference between the app administration and the association members management. e.G. the roles correspond to the administration, but the name and address to the management.

I will post the list of fields and for each of them, we will determine which type is it between administration and management.

**Comment by LucileDT** [comment]
![A merise scheme of the user's data](https://user-images.githubusercontent.com/23707217/58814412-f4c56580-8625-11e9-92e8-fec4059ad460.png)

```
ADDRESS: id, line, postal_code, city, country
USERS_ADDRESSES, 1N USER, 1N ADDRESS
DENOMINATION: id, label

LAST_UPDATER, 01 USER, 0N> USER
USER: id, username, password, first_name, last_name, email_address, home_phone_number, cell_phone_number, work_phone_number, work_fax_number, is_receiving_newsletter, newsletter_dematerialization, observations, medical_details, last_update_date
USERS_DENOMINATIONS, 01 USER, 0N DENOMINATION

RESPONSIBILITY: id, code, label, description
USERS_RESPONSIBILITIES, 1N USER, 1N RESPONSIBILITY
:
```

Field | Type
------------ | -------------
ADDRESS (line, postal_code, city, country) | management
id | administration
username | administration
password | administration
first_name | management
last_name | management
email_address | management
home_phone_number | management
cell_phone_number | management
work_phone_number | management
work_fax_number | management
is_receiving_newsletter | management
newsletter_dematerialization | management
observations | management
medical_details | management++
last_update_date | administration
DENOMINATION (label) | administration
RESPONSABILITY (code, label, description) | administration

**Comment by sapphaos** [comment]
Mockups for the admin part
![2019-06-04_15-52](https://user-images.githubusercontent.com/26595575/58885925-55ff3e80-86e3-11e9-9605-856387dcb943.png)
![2019-06-04_15-53](https://user-images.githubusercontent.com/26595575/58885926-55ff3e80-86e3-11e9-927a-597a8dcf538a.png)

Mockups for the manager part
![2019-06-04_15-50](https://user-images.githubusercontent.com/26595575/58885924-55ff3e80-86e3-11e9-9077-b689caade1e1.png)
![2019-06-04_15-54](https://user-images.githubusercontent.com/26595575/58885927-5697d500-86e3-11e9-9497-171d8411bb33.png)

Link to full mockup : https://app.moqups.com/tajXca9bxS/view/page/a757eb47f

**Comment by LucileDT** [comment]
We miss an edition form for the members on the page Adhérent.es > Edit

**Comment by Yann-BUTSCHER-EIRL** [comment]
People entity added by @LucileDT, Fixtures updated by @Yann-BUTSCHER-EIRL .

**Comment by sapphaos** [comment]
Edit user profile according to mockups.

![profile mockup](https://hostpic.xyz/files/1562333510748168932.png)
![edit roles](https://hostpic.xyz/files/15623336263329623627.png)
![edit sensible](https://hostpic.xyz/files/15623339651516076101.png)
![edit contact](https://hostpic.xyz/files/1562334166600021111.png)
![edit perso](https://hostpic.xyz/files/15623343192858923175.png)

Also change the Denomination field in the Edit/add member forms to https://symfony.com/doc/current/reference/forms/types/entity.html so it can be similar to a combobox.

**Comment by LucileDT** [comment]
I will close this big blob issue as we have a lot of thing in it that as be done. Improvements and/or bug will be listed in separated issues :)
