### ISSUE TITLE
Add another test in the push git hook

### ISSUE THREAD

**Issue by LucileDT** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/huntington-avenir-bdd#29]
# Context
We use Git Hooks to trigger some actions, like running tests before pushing. We need to add a PHPCS check which reads the PHP code and check if it's well formatted.

# Todo 
- [x] install PHPCS
- [x] configure PHPCS
  - [x] discuss about our code format
  - [x] configure it
  - [ ] look for solution for the remaining convention no yet tested
- [x] add the hook
