### ISSUE TITLE
Add a link to the CoC where it is useful

### ISSUE THREAD

**Issue by LucileDT** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/huntington-avenir-bdd#32]
# Context
We created and pushed a CoC for the project. We need to add links to this CoC where it is useful.

# Todo 
- [x] add a link in the Readme
- [x] add a link in the issue templates
  - [x] bug
  - [x] feature
- [x] add a link in the wiki > contribuer
