### ISSUE TITLE
Roles management

### ISSUE THREAD

**Issue by LucileDT** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/huntington-avenir-bdd#4]
# Context
User role allow to define which things a user can do. We need to setup the first version of role management: a "hard list" saved in database, used directly in the PHP code (users will not be able to create new roles and define what they can do in this version).

A role has:
- a public and unique id
- a code
- a label
- a description

# Todo
- [x] user has roles
- [x] roles definition
- [x] roles creation
- [x] limitation of access depending on the role
  - [x] admin
  - [x] other pages

**Comment by LucileDT** [comment]
#### Liste des différents rôles
- [ ] Administrateurice : gestion des comptes utilisateurices et des droits, D des données si demande d'un.e adhérent.e
- [ ] Gestionnaire de niveau 1 : accès aux profils adhérents, accès au parcours médical des adhérents, CRUA de toutes données, 
- [ ] Gestionnaire de niveau 2 : accès aux profils adhérents, CRUA de toutes données hors parcours de soin
- [ ] Informateurice : boutons permettant d'envoyer des mails (relances, newletters, ...)
- [ ] Adhérent.e : CRUA de son propre profil uniquement

**Comment by LucileDT** [comment]
```sql
INSERT INTO `responsability` VALUES
(1,'ROLE_ADMIN','Administrateurice de la base de données','Permet à l\'utilisateurice de créer, éditer et supprimer les comptes utilisateurs de la base de données.'),
(2,'ROLE_GESTIONNAIRE_1','Gestionnaire de niveau 1','Permet à l\'utilisateurice de voir toutes les informations de la base de données, de les éditer, de les supprimer et d\'en enregistrer de nouvelles (mis à part les comptes utilisateurices).'),
(3,'ROLE_GESTIONNAIRE_2','Gestionnaire de niveau 2','Permet à l\'utilisateurice de voir les informations des adhérent.e.s, de les éditer, de les archiver et d\'en enregistrer de nouvelles (mis à part le parcours médical)'),
(4,'ROLE_INFORMATEURICE','Informateurice','Permet à l\'utilisateurice d\'envoyer des mails automatiquement depuis le logiciel (relances, newletters...)'),
(5,'ROLE_ADHERENT_E','Adhérent.e','Permet à l\'utilisateurice de voir les informations de son compte, de les éditer, de les archiver et d\'en enregistrer de nouvelles');
```

**Comment by Yann-BUTSCHER-EIRL** [comment]
TODO : Update issue and comments to reflect the new organisation.

**Comment by sapphaos** [comment]
There are a few typos for some roles descriptions :
"renouveller" -> "renouveler"  for Adhérent.e and Ex-adhérent.e
"annuraire des professionels" -> "annuaire des professionnels" for Inscrit.e
