### ISSUE TITLE
Add nice display in the git hooks

### ISSUE THREAD

**Issue by LucileDT** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/huntington-avenir-bdd#49]
# Context
When the hooks are triggered, a serie of actions are run. I would like to:
- separate those action by big titles to make clear when an action is done and when a new starts,
- for the before push hook, add at the end of the hook a summary which shows if the hook failed.

# Todo
- [ ] design a separator between actions
- [ ] add the separator to the hooks
- [ ] design a message for the end of the before push hook
- [ ] add the message to the hook
