### ISSUE TITLE
Questions / TODO - Gestion utilisateurices

### ISSUE THREAD

**Issue by LucileDT** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/huntington-avenir-bdd#5]
- [x] qui sont les personnes/types de personnes qui vont utiliser le site ?
    - [x] définir les niveaux de rôle
    - [x] quel rôle donne accès à quoi ?
  - [x] voir la BDD existante
  - [x] comment set son mdp quand on a déjà un compte dans l'asso ?
  - [x] laisser les adhérent.e.s éditer leur profil ?
  - [x] reset de mot de passe ? (à faire peut-être plus tard, demander si c'est un besoin)
  - [x] création de profil ? (à faire sur un sprint 2 ? à voir la BDD existante ?)

**Comment by Parmifer** [comment]
Les adhérents peuvent éditer leurs profils.
Leur profil est créé par une personne de l'asso et leurs identifiants leurs sont envoyés par la suite.

**Comment by Parmifer** [comment]
Lors de la création du profil d'un adhérent, un code unique leur sera envoyé par mail pour qu'il puissent changer leur mdp.
