### ISSUE TITLE
Creation of error listing and error codes documentation

### ISSUE THREAD

**Issue by LucileDT** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/huntington-avenir-bdd#57]
# Context
Currently, we throws error messages when errors and exceptions occurs. We need to create more user friendly error messages and a system allowing amdins and devs to easily correct them when needed.

# Todo
- [ ] create a standard for error messages
  - [ ] error code
  - [ ] error labels
- [ ] create documentation about it
- [ ] update existing error messages with the new standard and error codes
