### ISSUE TITLE
User without personnal information cannot connect

### ISSUE THREAD

**Issue by LucileDT** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/huntington-avenir-bdd#58]
# Scenario
- create from the administration a new user
- disconnect and connect with the user newly created

# Expected behavior
- the home page is displayed

# Current behavior
- an exception occurs

![image](https://user-images.githubusercontent.com/23707217/61133136-19cab500-a4bd-11e9-875f-ff5a1b010573.png)

# TODO
- [ ] in UserController, create a new methode MyProfileAction and make the route use user.id
- [ ] edit the top menu to use in the Mon Profil entry the newly created route (with user.id)
- [x] create new view for Mon Profil (you can include partials that are used in other views)
- [x] in the views, check if the user.people is set. If it is: display the user.people data

**Comment by sapphaos** [comment]
How can we add a link to the profile without the id? The profile uses the people id to display most infos and retrieve the user id.

**Comment by LucileDT** [comment]
- [ ] in UserController, create a new methode MyProfileAction and make the route use user.id
- [ ] edit the top menu to use in the Mon Profil entry the newly created route (with user.id)
- [ ] create new view for Mon Profil (you can include partials that are used in other views)
- [ ] in the views, check if the user.people is set. If it is: display the user.people data
