### ISSUE TITLE
Run the test server on a different port than the default one

### ISSUE THREAD

**Issue by LucileDT** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/huntington-avenir-bdd#60]
# Context
To run the functional tests, we run a different server to use different configuration options. We should be able to run the dev server and the test server simultaneously at the same time, on different ports.

# Todo
- [ ] make the test server run on another port than the `8000` one
- [ ] if needed, update the tests
- [ ] if needed, update the documentation
