### ISSUE TITLE
Add a button allowing to delete an account from the users list

### ISSUE THREAD

**Issue by LucileDT** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/huntington-avenir-bdd#7]
# Context
Currently, we need to edit a user account to be able to delete it. We should be able to do it from the list, using a :wastebasket: button.

# Todo
- [x] add the button
- [x] confirmation rollover (`Do you really want to delete this account?` with Yes and Cancel buttons) (yellow)
- [x] Success message (green)

**Comment by LucileDT** [comment]
The color of the message in the confirmation modal should be yellow/orange (warning) and not red (error), as it is a warning message, not an error one.
