### ISSUE TITLE
Create home page items

### ISSUE THREAD

**Issue by hundrex** [LUCILE-DECROZANT-TRIQUENAUX-EIRL/huntington-avenir-bdd#89]
# Context
We want to have some useful informations on the manager's application home page, so they can quickly see important informations, or access recurring tasks. 

# Todo
- [x] People that didn't pay their subscription this year array: 
  - [x] Top label: `Ex-Adhérents à relancer`
  - [x] List of the 6 first users in alphabetic order
  - [x] Show user button
  - [x] Edit user button
  - [x] Pagination
- [x] A big button labelled `Enregistrer un contact` 
  - [x] redirects to the create member form
- [x] A big button labelled `Enregistrer une adhésion` 
  - [x] disabled with a tooltip
- [x] A big button labelled `Enregistrer un don`
  - [x] disabled with a tooltip
- [x] A chart that shows the donations and subscriptions amounts over the last 6 months 

For items placement and more details, see mockup below:
![image](https://user-images.githubusercontent.com/11696314/67638569-3bbe3b00-f8e6-11e9-9bf6-42182d4c5686.png)

**Comment by Yann-BUTSCHER-EIRL** [comment]
@LucileDT Can you configure pagination of the user table to only get 6 users per page please

**Comment by LucileDT** [comment]
First I add another button then I look how I can do that easily!

**Comment by LucileDT** [comment]
All is done!
